#cloud-config
coreos:
  update:
    ## NB: You should enable updates in production
    ## Terraform already takes care of static IPs
    ## in GCE, so it should be safe for weave nodes
    ## to rejoin after reboot
    reboot-strategy: 'off'
  units:
    - name: 10-weave.network
      runtime: false
      content: |
        [Match]
        Type=bridge
        Name=weave*
        [Network]

    - name: weave.service
      content: |
        [Unit]
        After=install-weave.service
        Description=Weave Network
        Documentation=http://zettio.github.io/weave/
        Requires=install-weave.service
        [Service]
        EnvironmentFile=/etc/weave.env
        ExecStartPre=/opt/bin/weave launch $WEAVE_PEERS
        ExecStartPre=/opt/bin/weave launch-dns $WEAVEDNS_ADDR
        ExecStart=/usr/bin/docker logs -f weave
        SuccessExitStatus=2
        ExecStop=/opt/bin/weave stop
        ExecStop=/opt/bin/weave stop-dns

    - name: install-weave.service
      command: start
      enable: true
      content: |
        [Unit]
        After=pre-fetch-container-images.service
        After=network-online.target
        After=docker.service
        Description=Install Weave
        Documentation=http://zettio.github.io/weave/
        Requires=pre-fetch-container-images.service
        Requires=network-online.target
        Requires=docker.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/bin/mkdir -p /opt/bin/
        ExecStartPre=/usr/bin/curl \
          --silent \
          --location \
          https://github.com/zettio/weave/releases/download/latest_release/weave \
          --output /opt/bin/weave
        ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
        ExecStart=/bin/echo Weave Installed

    - name: pre-fetch-container-images.service
      command: start
      enable: true
      content: |
        [Unit]
        After=docker.service
        Requires=docker.service
        [Service]
        EnvironmentFile=/etc/pre-fetch-container-images.env
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/sh -c 'for i in $PRE_FETCH_CONTAINER_IMAGES; do /usr/bin/docker pull $i; done'

write_files:
  - path: /etc/pre-fetch-container-images.env
    permissions: 0644
    owner: root
    content: |
      PRE_FETCH_CONTAINER_IMAGES="\
        zettio/weave:latest \
        zettio/weavedns:latest \
        zettio/weavetools:latest \
      "
#  - path: /etc/weave.env
#    permissions: 0600
#    owner: root
#    content: |
#      WEAVE_PEERS="${peers}"
#      WEAVE_PASSWORD="${crypt}"
#      WEAVEDNS_ADDR="10.10.2.1${count}/16"
